# Generated by Django 3.2.6 on 2021-08-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_special',
        ),
        migrations.RemoveField(
            model_name='user',
            name='min_budget',
        ),
        migrations.AlterField(
            model_name='user',
            name='max_budget',
            field=models.PositiveBigIntegerField(),
        ),
    ]
