# Generated by Django 3.2.6 on 2021-08-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210828_0809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealer',
            options={'verbose_name': 'مشاور', 'verbose_name_plural': 'مشاوران'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterField(
            model_name='dealer',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='first_name',
            field=models.CharField(max_length=60, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='last_name',
            field=models.CharField(max_length=60, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=60, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=60, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='max_budget',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='حداکثر بودجه'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('O', 'مالک'), ('B', 'خریدار')], max_length=1, verbose_name='وضعیت'),
        ),
    ]
