# Generated by Django 3.2.6 on 2021-09-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210829_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='num_of_people',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد نفرات'),
        ),
    ]
