# Generated by Django 3.2.6 on 2021-09-15 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_num_of_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dealer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registered_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
