# Generated by Django 3.2.6 on 2021-08-22 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_type', models.CharField(choices=[('R', 'Rent'), ('S', 'Sale')], max_length=1)),
                ('property_type', models.CharField(choices=[('A', 'Apartment'), ('H', 'House')], max_length=1)),
                ('floor', models.SmallIntegerField(default=0)),
                ('location', models.TextField()),
                ('total_area', models.PositiveSmallIntegerField()),
                ('building_area', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_built', models.DateField()),
                ('price', models.PositiveBigIntegerField()),
                ('options', models.CharField(max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='account.user')),
                ('requesters', models.ManyToManyField(related_name='requested_properties', to='account.User')),
            ],
        ),
    ]
