# Generated by Django 3.2.6 on 2021-08-29 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210829_0636'),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی',
            },
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'ملک', 'verbose_name_plural': 'املاک'},
        ),
        migrations.AlterField(
            model_name='property',
            name='building_area',
            field=models.PositiveSmallIntegerField(verbose_name='متراژ زیربنا'),
        ),
        migrations.AlterField(
            model_name='property',
            name='date_built',
            field=models.DateField(verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor',
            field=models.SmallIntegerField(default=0, verbose_name='طبقه'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='تصاویر'),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.TextField(verbose_name='آدرس'),
        ),
        migrations.RemoveField(
            model_name='property',
            name='options',
        ),
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='account.user', verbose_name='مالک'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.PositiveBigIntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('A', 'Apartment'), ('H', 'House')], max_length=1, verbose_name='نوع ملک'),
        ),
        migrations.AlterField(
            model_name='property',
            name='requesters',
            field=models.ManyToManyField(related_name='requested_properties', to='account.User', verbose_name='متقاضیان'),
        ),
        migrations.AlterField(
            model_name='property',
            name='sale_type',
            field=models.CharField(choices=[('R', 'Rent'), ('S', 'Sale')], max_length=1, verbose_name='نوع واگذاری'),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_area',
            field=models.PositiveSmallIntegerField(verbose_name='متراژ کل'),
        ),
        migrations.AddField(
            model_name='property',
            name='options',
            field=models.ManyToManyField(to='property.Options', verbose_name='امکانات'),
        ),
    ]
