# Generated by Django 3.2.6 on 2021-09-03 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_num_of_people'),
        ('property', '0002_auto_20210829_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'status': 'O'}, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='account.user', verbose_name='مالک'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('A', 'آپارتمان'), ('H', 'ویلایی')], max_length=1, verbose_name='نوع ملک'),
        ),
        migrations.AlterField(
            model_name='property',
            name='requesters',
            field=models.ManyToManyField(blank=True, limit_choices_to={'status': 'B'}, related_name='requested_properties', to='account.User', verbose_name='متقاضیان'),
        ),
        migrations.AlterField(
            model_name='property',
            name='sale_type',
            field=models.CharField(choices=[('R', 'اجاره'), ('S', 'فروش')], max_length=1, verbose_name='نوع واگذاری'),
        ),
    ]
